#!/bin/sh

unamestr=`uname`
CURRENT_DIR=$(pwd)
ETC_DIR=$HOME/etc
CONF_DIR=$HOME/.config


if [[ "$unamestr" == 'Linux' ]]; then
  # Create etc directory if not exist
  if [ ! -d "$ETC_DIR" ]; then 
    mkdir $ETC_DIR
  fi


if [ ! -d "$ETC_DIR" ]; then 
  mkdir $ETC_DIR
fi

for i in $CURRENT_DIR/* ; do
  if [ -d "$i" ]; then
    if [ ! -d "$ETC_DIR/$(basename "$i")" ]; then 
      echo "created "$(basename "$i")
      ln -s $CURRENT_DIR/$(basename "$i") $ETC_DIR/$(basename "$i")
    else 
      echo "directory already exists"
    fi
  fi
done

 elif [[ "$unamestr" == 'Darwin' ]]; then

  if [ ! -d "$CURRENT_DIR/$CON_DIR/git" ]; then 
    echo "git config made!"
    ln -s $CURRENT_DIR/git $CONF_DIR/git
  else
    echo "This config already exists"
  fi

  if [ ! -d "$HOME/.sh.d" ]; then 
    echo ".sh.d made!"
    ln -s $CURRENT_DIR/mksh/sh.d $HOME/.sh.d
  else 
    echo "This config already exists"
  fi

  if [ ! -f "$HOME/.mkshrc" ]; then 
    echo "mksh config made!"
    ln -s $CURRENT_DIR/mksh/mkshrc $HOME/.mkshrc
  else 
    echo "This config already exists"
  fi

  if [ ! -d "$HOME/.config/nvim" ]; then 
    echo "nvim config made!"
    ln -s $CURRENT_DIR/nvim $CONF_DIR/nvim
  else 
    echo "This config already exists"
  fi

  if [ ! -f "$HOME/.tmux.conf" ]; then 
    echo "tmux config made!"
    ln -s $CURRENT_DIR/tmux/tmux.conf $HOME/.tmux.conf
  else 
    echo "This config already exists"
  fi

fi




